version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "minimatch"
        update-types: ["version-update:semver-major"]
    groups:
      deps-dev:
        dependency-type: "development"
      deps-prod:
        dependency-type: "production"

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 3


