version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 0
    groups:
      deps-dev:
        dependency-type: "development"
      deps-prod:
        dependency-type: "production"

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 0


